// Added feature 1

pipeline{
  agent any
  stages {
   stage('clone project') {
      steps {
           git branch:'master', url:'https://github.com/khwazabani/Amazon.git'
   }
}
   stage('compile') {
      steps {
          dir('Amazon')
          {
           sh 'mvn compile'
       }
   }
   }
   stage('test') {
      steps {
          dir('Amazon')
          {
           sh 'mvn test'
       }
      }
   }

   stage('build') {
      steps {
          dir('Amazon'){
           sh 'mvn clean install'
       }
   }
}
  }


   post {
    success {
      mail to: 'buildkhwazabani@gmail.com',
           subject: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
           body: "The build succeeded. See ${env.BUILD_URL}"
    }
    failure {
      mail to: 'buildkhwazabani@gmail.com',
           subject: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
           body: "The build failed. See ${env.BUILD_URL}"
    }
  }

}



